server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # 使用动态路由需要将uri改成服务名称
      routes:
        - id : payment_routh
          uri: lb://cloud-payment-service
          predicates:  # 断言 路径相匹配进行路由
            - Path=/payment/get/**

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/**

eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
